name: Build and Run

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Run s4_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s4_challenge

    - name: Run s6_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s6_challenge

    - name: Run s7_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s7_challenge

    - name: Run s8_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s8_challenge

    - name: Run s9_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s9_challenge

    - name: Run s10_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s10_challenge

    - name: Run s11_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s11_challenge

    - name: Run s12_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s12_challenge

    - name: Run s13_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s13_challenge

    - name: Run s14_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s14_challenge

    - name: Run s15_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s15_challenge

    - name: Run s16_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s16_challenge

    - name: Run s17_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s17_challenge

    - name: Run s18_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s18_challenge

    - name: Run s19_1_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s19_1_challenge

    - name: Run s19_2_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s19_2_challenge

    - name: Run s19_3_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s19_3_challenge

    - name: Run s19_4_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s19_4_challenge

    - name: Run s20_1_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s20_1_challenge

    - name: Run s20_2_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s20_2_challenge

    - name: Run s20_3_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s20_3_challenge

    - name: Run s20_4_challenge
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: beginner_tutorial
        bin: s20_4_challenge

    - name: Run builder
      run: cd ./build/$sub_project/$bin && ./$bin
      env:
        sub_project: design_patterns
        bin: builder
