name: Build and Run

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Run s4_challenge
      run: ./build/s4_challenge/s4_challenge

    - name: Run s6_challenge
      run: ./build/s6_challenge/s6_challenge

    - name: Run s7_challenge
      run: ./build/s7_challenge/s7_challenge

    - name: Run s8_challenge
      run: ./build/s8_challenge/s8_challenge

    - name: Run s9_challenge
      run: ./build/s9_challenge/s9_challenge

    - name: Run s10_challenge
      run: ./build/s10_challenge/s10_challenge

    - name: Run s11_challenge
      run: ./build/s11_challenge/s11_challenge

    - name: Run s12_challenge
      run: ./build/s12_challenge/s12_challenge

    - name: Run s13_challenge
      run: ./build/s13_challenge/s13_challenge

    - name: Run s14_challenge
      run: ./build/s14_challenge/s14_challenge

    - name: Run s15_challenge
      run: ./build/s15_challenge/s15_challenge

    - name: Run s16_challenge
      run: ./build/s16_challenge/s16_challenge

    - name: Run s17_challenge
      run: ./build/s17_challenge/s17_challenge

    - name: Run s18_challenge
      run: ./build/s18_challenge/s18_challenge

    - name: Run s19_1_challenge
      run: ./build/s19_1_challenge/s19_1_challenge

    - name: Run s19_2_challenge
      run: |
        cd ./build/s19_2_challenge
        ./s19_2_challenge
